frontend:
  name: frontend
  image:
    repository: heschmat/movies-fe
    tag: "60c0504a81d808d8aa968b89720209cd42e6be7b"
  containerPort: 3000
  servicePort: 80
  env:
    REACT_APP_MOVIE_API_URL: ""

backend:
  name: backend
  image:
    repository: heschmat/movies-be
    tag: "60c0504a81d808d8aa968b89720209cd42e6be7b"
  containerPort: 5000
  servicePort: 80
  readinessPath: /movies
  livenessPath: /movies

ingress:
  enabled: true
  name: movies-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
  ingressClassName: alb
