apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: heschmat/movies-be:v2
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /movies
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /movies
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 5
